### ISSUE TITLE
[ETC] : AED데이터 관련 

### ISSUE THREAD

**Issue by jjoohee95** [Kim-Dong-Hyeon/Duriso#56]
## 어떤 문제인가요?

> aed api 요청변수에 위경도 값을 지정해주는 요청변수가 없다보니
전체 데이터를 받아와서 거기서 가시성 조율을 하기에는 데이터가 너무 많은데 어떻게 하면 좋을까요?

## 생각한 방안
1. 페이지당 1000개의 데이터를 받아올 수 있는데 최대 페이지로 받아와서 거기서 2km반경을 계산한다
2. 서버에 개선 요청을 한다
3. 전체 데이터를 저장한 후 거기서 필터링해서 한다

**Comment by Kim-Dong-Hyeon** [comment]
제 의견은
2번 신청은 해보고 반영시간이 있을테니 그동안은 3번으로 구현해놓는게 가장 간단하지 않을까요?
근데 저장보다는 임시 저장 느낌으로 하면 좋을 것 같습니다.
앱 실행시킬때 데이터를 불러와서 임시로 저장해서 필터링이요!
