### ISSUE TITLE
[Agenda] 커뮤니티 내 디폴트 이미지가 있으면 좋겠다 & 없으면 좋겠다

### ISSUE THREAD

**Issue by shinsangkyu6660** [Kim-Dong-Hyeon/Duriso#65]
## 어떤 문제인가요?

> 커뮤니티 tableView에서 디폴트 이미지가 있으면 좋겠다 & 없으면 좋겠다

## 생각한 방안
- [ ] 당근마켓경우 디폴트 이미지가 있음
- [ ] 없으면 비어보인다는 의견
- [x] 없으면 깔끔하다는 의견

## 참고할만한 자료(선택)
<img alt="IMG_3379" src="https://github.com/user-attachments/assets/ffc1375c-eb47-420b-a78e-1d55750a96e4" width="30%">
<img width="250" alt="스크린샷 2024-09-14 오전 3 34 51" src="https://github.com/user-attachments/assets/9301c965-a585-426c-aa1a-ba16cb29bb06">
<img width="270" alt="스크린샷 2024-09-14 오전 3 38 57" src="https://github.com/user-attachments/assets/1e8d79ad-ba87-4904-8610-080d4fb75487">

**Comment by Kim-Dong-Hyeon** [comment]
@shinsangkyu6660 

- 음.. 제 의견은 사용자가 사진을 추가하지 않고 제보를 했을 때는 사용자의 의도대로 아무 사진 없이 띄워주는 것이 조금 더 맞다고 생각합니다!🤔
- Default 이미지를 앱에서 임의로 지정해버리면 UI 면에서는 좋을 수 있겠으나 UX 측면에서는 우리 서비스의 목적인 정확한 정보 전달이 어려울 수 있고 정보전달이 중간에 왜곡될 수도 있다고 봅니다😥

**Comment by HwaN310** [comment]
전 아무 정보도 없으면 빈 화면이 뜨는게 좋지 않을까 싶습니다. 의미없는 디폴트 이미지를 넣었을 때 이 기본으로 설정된 내용이 재난과 관련된 내용일 경우 혼란을 줄 수도 있고 아예 관련없는 제목, 내용, 00시 00구 00동 00분전이라고 작성된 내용이 기본으로 떠 있을 때 미완성으로 보이지 않을까..싶습니다.

저는 공지사항을 구현중인데 공지사항에 아무 내용이 없을 땐 화면 중앙에 "공지사항 없음"이라는 문구를 라벨로 띄워두려고 하는데 커뮤니티에서도 정보가 전혀 없을 때 내용이 없다는 걸 화면 중앙에 라벨로 띄워두는게 좋지 않을까 싶습니다.
문구만 넣어두기엔 비어보인다면 간단한 이미지를 추가하면 비어보이는 느낌을 지울 수 있지 않을까 싶습니다.

**Comment by jjoohee95** [comment]
사진보다 정보전달 목적이니까 비어두는것도 좋다고 생각이 드는데

사진이 비었을 때 그 자리를 내용이 채워주는게 아니라 그냥 하얀 배경색으로 자리를 비워두는 것이라면 
목업 이미지로 들어가는 것도 나쁘지 않은 것 같습니다.

만약 사진으로 채운다면 어떤 이미지가 들어가야 할 지 더 논의가 필요해 보여요!

**Comment by Kim-Dong-Hyeon** [comment]
> 사진보다 정보전달 목적이니까 비어두는것도 좋다고 생각이 드는데
> 
> 사진이 비었을 때 그 자리를 내용이 채워주는게 아니라 그냥 하얀 배경색으로 자리를 비워두는 것이라면 목업 이미지로 들어가는 것도 나쁘지 않은 것 같습니다.
> 
> 만약 사진으로 채운다면 어떤 이미지가 들어가야 할 지 더 논의가 필요해 보여요!

@jjoohee95 

- 제가 우려하는 부분은 사용자가 카테고리를 잘못 선택하고 글을 작성했을 경우입니다.😅
ex) 지진인데 정신 없는 상황에서 태풍으로 카테고리를 잘못 선택한 후 이미지 없이 내용 작성 -> 태풍 목업 이미지 띄워짐 -> 다른 사용자들은 태풍 목업 사진만으로는 태풍으로 착각 가능성 있음.😥

**Comment by shinsangkyu6660** [comment]
> > 사진보다 정보를 전달하려는 목적이 에너지인 것 같다고 생각합니다.
> > 사진이 비일 것 같다면 그 자리를 내용이 에너지 주는 게 아니라 그냥 하얀 배경색으로 자리를 비워두는 것이라면 목업 이미지로 하는 것도 나쁘지 않은 것 같습니다.
> > 만약 사진으로 채운다면 어떤 이미지가 참여해야 할지 더 이야기가 필요해 보여주세요!
> 
> @jjoohee95
> 
> * 제가 주위에 있는 부분은 사용자가 카테고리를 잘못 선택하고 글을 작성한 경우였습니다.😅 
>   ex) 지진이 없는 상황에서 드라이버로 카테고리를 잘못 처리한 후 이미지 없이 내용 작성 -> 드라이브 목업 이미지 띄워짐 -> 다른 그들은 구동 목업 사진으로 인해 효과가 있을 가능성이 있습니다.😥

@Kim-Dong-Hyeon 
의견은 나쁘지 않지만 기본 로고 이미지 들어가는것도 괜찮을것 같아요 추후 한번 보고 결정하시죠
