### ISSUE TITLE
[Bug] poiID 디버그 출력 Issue

### ISSUE THREAD

**Issue by Kim-Dong-Hyeon** [Kim-Dong-Hyeon/Duriso#68]
## 어떤 버그인가요?

> 앱 실행 디버그 출력 시 poiID에서 장소명으로 출력되는 부분이 있는 것 같습니다.

## 어떤 상황에서 발생한 버그인가요?

> 앱 실행 디버그 출력 시 poiID 부분 출력되는 곳에 한글 장소명으로 된 부분이 발견되었습니다.

## 예상 결과

> poiID가 모두 숫자로 되어있는 것인 줄 알았습니다.

## 참고할만한 자료(선택)
<img width="789" alt="image" src="https://github.com/user-attachments/assets/ce1eed46-ce43-4e32-b1b6-91bf5ed5d2a7">

**Comment by jjoohee95** [comment]
poiID 숫자 출력되는건 AED POIID, 한글로 출력되고 있는건 대피소 POIID입니당

대피소는 api정보중 대피소 명이 존재하는데 aed는 시리얼 넘버만 존재하고이름이 따로 존재하지 않아서
시러얼 넘버로 출력되고 있는거고 대피소는 대피소 명이 따로 있어서 구분이 용이하도록 
대피소 명으로 출력되도록 해두었습니다!😁😁

**Comment by Kim-Dong-Hyeon** [comment]
@jjoohee95 

아하! 확인했습니다😁
대피소 명으로 구분하면서 생기는 이슈는 따로 없었나요!?🤔 ex) 이름 중복 이슈 등등

**Comment by jjoohee95** [comment]
네네

**Comment by Kim-Dong-Hyeon** [comment]
@jjoohee95

주희님 요기 부분 이름 같은데 아마 요기서 어떻게 출력되는지 확인 해보면 될것같아요!
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/cb051b89-f877-448e-875a-cce7876d490d">

**Comment by jjoohee95** [comment]
확인했습니당~
